### PR TITLE
Integrated Deriv/Folder Structure

### PR DESCRIPTION
**Pull request by carlsonb99**
- Made folder structure for easier viewing/placement of files
- Adjusted includes for structure
- Integrated 'deriv' keyword/procedure into backend
- Updated GUI to clear canvas on new input

Problems
- deriv either returns a number or list in prefix form. I don't have a
  way of converting it back to infix, or a clean way to convert that list
  into a readable string at the moment.

### CODE REVIEW

**Comment by norman2005** [comment]
brian what about if we can return the list in infix form ? will that be
better?

Regards ,
Norms.

**Comment by carlsonb99** [comment]
yeah, if you can rework the deriv function to list in "infix" notation,
that would be best, since I can easily convert that to a readable string
output.

**Comment by norman2005** [comment]
ok . let me see how quickly i can do that .

Regards ,
Norms.

**Comment by norman2005** [comment]
dude i can seem to get a clean way of doing it without the failing the
tests cases ..... will keep looking into it.

Regards ,
Norms.

**Comment by norman2005** [comment]
i mean i cant find a clean way to change from prefix to infix without
generating errors .

Regards ,
Norms.

**Comment by carlsonb99** [comment]
Ok

**Comment by norman2005** [comment]
Guys can i get both of your  Favorite Lines of Code

Each team member should identify a favorite line of code, expression, or
procedure written by them, and explain what it does. Why is it your
favorite? What OPL philosophy does it embody? Remember code looks something
like this:

(map (lambda (x) (foldr compose functions)) data)

Regards ,
Norms.

**Pull request merged**
